In [1]:
import jax
from jax import jit
import jax.numpy as jnp

from polynomials.PolynomialRing import make_polynomial_ring
from ckks.utils import *

In [2]:
PR = make_polynomial_ring(15, 4)

In [3]:
PR.sample_gaussian(1, seed=2)

Polynomial ring: [ 0. -1.  0. -2.] (mod 15), reminder range: (-8, 7]

In [4]:
rp1 = PR(jnp.array([1,2,3,4]))
rp2 = PR(jnp.array([1,2,3,4]))

In [5]:
x = jnp.array([1,2,3,4])
shift_mod(ring_polymul(x, x, get_modulo(4))[-4:], 15)

DeviceArray([ 5., -6.,  5.,  6.], dtype=float32)

In [6]:
rp1 * rp2

Polynomial ring: [ 5. -6.  5.  6.] (mod 15), reminder range: (-8, 7]

In [7]:
rp1*rp2

Polynomial ring: [ 5. -6.  5.  6.] (mod 15), reminder range: (-8, 7]

In [8]:
shift_mod(jnp.array([14,2,3]), 15)

DeviceArray([-1,  2,  3], dtype=int32)

In [9]:
RingPolynomial(jnp.array([6,2,3]), 15, 3)

NameError: name 'RingPolynomial' is not defined

In [10]:
def shift_mod(x, modulo):
    modulo_half = modulo // 2
    return jnp.mod(x + modulo_half, modulo) - modulo_half

In [11]:
list(range(-7, 8))

[-7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7]

In [12]:
import numpy as np

n = 8  # power of 2
q = 67108289  # prime number, q = 1 (mod 2n)
t = 37  # prime number, t < q
std = 3  # standard deviation of Gaussian distribution

m0 = PR(np.random.randint(t, size=n), t)  # plaintext
m1 = PR(np.random.randint(t, size=n), t)  # plaintext


In [18]:
x = np.random.randint(t, size=n)
x

array([ 1, 32, 31,  9, 17, 17, 11, 27])

In [20]:
x

array([ 1, 32, 31,  9, 17, 17, 11, 27])

In [22]:
PR = make_polynomial_ring(30001, 8)
m = PR(x)
m

Polynomial ring: [ 1 32 31  9 17 17 11 27] (mod 30001), reminder range: (-15001, 15000]

In [23]:
m * m

Polynomial ring: [ 2118.  3004.  2386.    63.  -710.  -532. -1086. -1516.] (mod 30001), reminder range: (-15001, 15000]