In [1]:
from jax.config import config
config.update("jax_enable_x64", True)
import jax
from jax import jit
import jax.numpy as jnp

from polynomials.PolynomialRing import make_polynomial_ring
from ckks.rlwe import RLWE
from ckks.utils import *

In [60]:
rlwe = RLWE(4, 67108289, 1001, 3)
sec = rlwe.PR_c(jnp.array([ 1, -1,  2,  1]))
pub = (
    rlwe.PR_c(jnp.array([16687756,  11294722,   1219612, -18590038])),
    rlwe.PR_c(jnp.array([-5940686, -17455659,  24384499, -18559542]))
)

m1 = jnp.array([11,22,33,44])  # plaintext
m2 = jnp.array([1,2,3,4])

In [61]:
c1, c2 = rlwe.encrypt(m1, pub), rlwe.encrypt(m2, pub)

In [62]:
cmul = rlwe.mul(c1,c2)
cmul

(Polynomial ring: [-17007018  33015667  18969724   -541037] (mod 67108289), reminder range: (-33554145, 33554144],
 Polynomial ring: [-28561157  18335964 -19289857 -30819462] (mod 67108289), reminder range: (-33554145, 33554144],
 Polynomial ring: [ 23695975  -3737475 -25717581  19021729] (mod 67108289), reminder range: (-33554145, 33554144])

In [64]:
rlwe.decrypt(cmul, sec)

Polynomial ring: [297 418 451 297] (mod 1001), reminder range: (-501, 500]

In [4]:
c = [
    rlwe.PR_c(jnp.array([-1833553, 33259835, -8886793,  7344785], dtype=jnp.int64)),
    rlwe.PR_c(jnp.array([-4714838,  14354028,  14740381, -18264677], dtype=jnp.int64)),
]

In [5]:
c = [ci * sec**i for i, ci in enumerate(c)]
m = c[0]
print(m)
for i in range(1, len(c)):
    m += c[i]
m

Polynomial ring: [-1833553. 33259835. -8886793.  7344785.] (mod 67108289), reminder range: (-33554145, 33554144]


Polynomial ring: [186. 224.   3. -33.] (mod 67108289), reminder range: (-33554145, 33554144]

In [33]:
sec

Polynomial ring: [1 2 3 4] (mod 67108289), reminder range: (-33554145, 33554144]

In [32]:
c[1]

Polynomial ring: [-10932312. -12931268.  27334992. -15933692.] (mod 67108289), reminder range: (-33554145, 33554144]

In [31]:
c[1] * sec

Polynomial ring: [ 23321524.   9344832.  29226496. -32410288.] (mod 67108289), reminder range: (-33554145, 33554144]

In [36]:
rlwe.decrypt(c, sec)

Polynomial ring: [  6. -15.  10.   1.] (mod 37), reminder range: (-19, 18]

In [5]:
sec = rlwe.PR_c(jnp.array([1, 2, 3, 4]))

In [14]:
c = rlwe.encrypt(m0, pub)
rlwe.decrypt(c, sec)

Polynomial ring: [ 24.  18. -19. -21.] (mod 51), reminder range: (-26, 25]

In [15]:
c

(Polynomial ring: [-15665732. -17972076.  14157416.  -5967392.] (mod 67108289), reminder range: (-33554145, 33554144],
 Polynomial ring: [ 22481176.  -9825540.  15656804. -10568664.] (mod 67108289), reminder range: (-33554145, 33554144])

In [33]:
c0 = rlwe.encrypt(m0, pub)
c1 = rlwe.encrypt(m1, pub)

m_0 = rlwe.decrypt(c0, sec)
m_1 = rlwe.decrypt(c1, sec)


In [34]:
c_add = rlwe.add(c0, c1)
rlwe.decrypt(c_add, sec)

Polynomial ring: [1112. 2012. 3008. 4010.] (mod 300001), reminder range: (-150001, 150000]

In [30]:
c_mul = rlwe.mul(c0, c1)
rlwe.decrypt(c_mul, sec)

Polynomial ring: [-10. -17. -17.   5.] (mod 37), reminder range: (-19, 18]

In [29]:
m_0

Polynomial ring: [11112. 22222. 33332. 44444.] (mod 300001), reminder range: (-150001, 150000]

In [17]:
rlwe.generate_keys()

(Polynomial ring: [ 4. -2.  0. -2.] (mod 67108289), reminder range: (-33554145, 33554144],
 (Polynomial ring: [-15665892. -17972024.  14157384.  -5967360.] (mod 67108289), reminder range: (-33554145, 33554144],
  Polynomial ring: [ 22481176  -9825540  15656803 -10568717] (mod 67108289), reminder range: (-33554145, 33554144]))

In [32]:
m0

array([19, 10, 17, 10,  6,  8, 24, 36])

In [91]:
import numpy as np

n = 8  # power of 2
q = 67108289  # prime number, q = 1 (mod 2n)
t = 37  # prime number, t < q
std = 3  # standard deviation of Gaussian distribution

rlwe = RLWE(n, q, t, std)
(sec, pub) = rlwe.generate_keys()

m0 = np.random.randint(50, size=n)  # plaintext
m1 = np.random.randint(50, size=n)  # plaintext

rm0 = rlwe.PR_p(m0)
rm1 = rlwe.PR_p(m1)

c0 = rlwe.encrypt(m0, pub)
c1 = rlwe.encrypt(m1, pub)

m_0 = rlwe.decrypt(c0, sec)
m_1 = rlwe.decrypt(c1, sec)

print(rm0)
print(m_0)
print()

print(rm1)
print(m_1)
print()

print('# Add')
print(rm0 + rm1)

c_add = rlwe.add(c0, c1)
m_add = rlwe.decrypt(c_add, sec)
print(m_add)
print()

print('# Mul')
print(rm0 * rm1)

c_mul = rlwe.mul(c0, c1)
m_mul = rlwe.decrypt(c_mul, sec)
print(m_mul)
print()


Polynomial ring: [ 7 17 11  2 -6  6  9 12] (mod 37), reminder range: (-19, 18]
Polynomial ring: [ 7 17 11  2 -6  6  9 12] (mod 37), reminder range: (-19, 18]

Polynomial ring: [ 12  18   0   1 -14   4  13  -4] (mod 37), reminder range: (-19, 18]
Polynomial ring: [ 12  18   0   1 -14   4  13  -4] (mod 37), reminder range: (-19, 18]

# Add
Polynomial ring: [-18  -2  11   3  17  10 -15   8] (mod 37), reminder range: (-19, 18]
Polynomial ring: [-18  -2  11   3  17  10 -15   8] (mod 37), reminder range: (-19, 18]

# Mul
Polynomial ring: [ -9   9  -3  15   0  -1 -15 -12] (mod 37), reminder range: (-19, 18]
Polynomial ring: [ -9   9  -3  15   0  -1 -15 -12] (mod 37), reminder range: (-19, 18]



In [73]:
m0, m1

(array([47, 15, 41, 42, 42, 20, 26,  1]),
 array([43, 49,  9, 19, 21, 32, 40, 15]))