In [1]:
import os
# os.environ['CUDA_VISIBLE_DEVICES']='1'

from jax.config import config
config.update("jax_enable_x64", True)
import jax
from jax import jit
from functools import reduce
import jax.numpy as jnp

from polynomials.pr_func import make_polynomial_ring_fn

In [3]:
n = 80
q = 671082899

PRFN = make_polynomial_ring_fn(n)

In [24]:
jk = jax.random.PRNGKey(0)
p1 = jax.random.randint(jk, (n,), -9999, 9999)
jk = jax.random.PRNGKey(1)
p2 = jax.random.randint(jk, (n,), -9999, 9999)

In [25]:
PRFN.mul(q, p1, p1, p1, p1)

DeviceArray([ -10509518,  171631148,  331747488, -221428672,  264388553,
              227949274,     803795,  144377882,  135526307, -173098901,
              -78523087, -215862503,  -69085383,  290994558,  153106816,
              -83718296,  213051668, -297823320,  210537102,   99539234,
             -195160625,  312635058, -278846797,   42934268,  -69340988,
                2943196,  295306118,  329293125,  -55528203,  107669239,
               15741122,  113798565,  308692968,  105404837, -120091915,
               73019056,  -97571631, -139040527,  169814642,  330781628,
               75615807,  111456949,    2855573,  -50163236, -229139113,
              119423271,    3765193,  -17271419,  -51536170,  172973390,
               55820790,  234351653,  171185714, -177881291,  -29577091,
                2413924, -301282291, -190850430, -294284398, -175371203,
             -172518328, -160814389, -240529566, -204882254,  286901137,
             -125243920, -305357218, -153321565,   

In [26]:
@jit
def test(x, y):
    xy = PRFN.mul(x, y)
    return PRFN.add(xy, xy)

test(p1, p2)

DeviceArray([ 6552,  7342,  5401, -3663,  3711,  -654,  3781, -2309,
             -1819,  9242,  5305,  5380,   208, -7748, -3115,  3478,
             -3695, -8494, -5604,  -846, -1962, -1779,  2688,  9698,
             -8193, -9895,  8472, -1306, -1340,  7711, -1192,  4981,
              4832,  5136,  2434, -8166,  4218, -5128,  1204,  5733,
             -6400,  1060,  8633,  6236,  3302,  2388,  8803,  5525,
              1424,  1290, -8407,  6549, -6214, -5366, -2352, -4962,
             -4723, -8523,  1227, -9175, -7211,  4136,  6088,  2282,
              6529, -4779,  3295,  1061,  5070,  2535,  6312, -8891,
             -5917,  6256, -5622,  -832,   390,  7734,  2864,  7004],            dtype=int64)

In [27]:
PRFN.add(p1, p2, p1, p2, p1, p1, p2, PRFN.mul(p1, p2, p1))

DeviceArray([  794,  2488,  1593,  1576, -1509,    27,    11,  2031,
              -451, -1503,  1768,  2120,  -242,  -139, -2465, -1615,
              -193,    38, -1817,  1639, -1850,  -797,  -813,  -538,
             -1180,  1111,    19, -2608,  -261,     3,  1776,  2684,
              1977, -2838, -1538, -2753,  -320,   146,  1953,   348,
              1498,   544,    73,    35,    63,   617,  -660,    -1,
               386,  2607,  2902,   659,   696,  1169,  -830, -1276,
              1207,  2005,  -610,   -89,  -185,  -462,   216,  -187,
             -3201, -1270,   346,   752, -3178,  1239,  2842,  -478,
              4016,   109, -4120,  1108, -2173,   252,   457,   696],            dtype=int64)

In [28]:
jax.random.choice(jax.random.PRNGKey(4), jnp.array([-1, 0, 1]), (80,), p =jnp.array([0.25, 0.5, 0.25]))

DeviceArray([ 0, -1,  0, -1,  0, -1,  0,  0,  1,  0,  0,  1, -1,  0,  0,
             -1,  0,  0, -1,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,
             -1,  0,  0,  0,  1,  1,  1, -1,  0, -1, -1,  1,  0, -1,  0,
              0,  1,  0,  1,  0,  0,  1,  0,  1,  0,  0,  0, -1,  1, -1,
              1, -1, -1, -1, -1,  0,  0,  0,  0,  0,  1,  0,  0,  0, -1,
             -1,  0,  1, -1,  1], dtype=int64)

In [4]:
PRFN.sample_HWT(1)

TypeError: Using a non-tuple sequence for multidimensional indexing is not allowed; use `arr[array(seq)]` instead of `arr[seq]`. See https://github.com/google/jax/issues/4564 for more information.

In [7]:
tuple(ix)

(49, 53, 5, 33, 65, 62, 51, 38, 61, 45)

In [21]:
coeffs.shape

(20,)

In [28]:
coeffs

DeviceArray([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
             0., 0., 0., 0., 0.], dtype=float64)

In [33]:
coeffs.at[0]

_IndexUpdateRef(DeviceArray([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
             0., 0., 0., 0., 0.], dtype=float64), 0)

In [38]:
import random
random.seed(1)
ix = tuple(random.sample(range(20), 10))
coeffs = jnp.zeros(20)
for i in ix:
    coeffs = coeffs.at[i].set(random.sample([-1,1],1)[0])
coeffs

DeviceArray([ 0.,  0., -1., -1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,
              1.,  1., -1.,  0.,  0.,  0., -1.,  0.], dtype=float64)